a = input("Digite Algo: ")
print("O tipo primitivo desse valor é ", type(a))
print("Só tem espaço? ", a.isspace())
print("É um numero? ", a.isnumeric())
print("É alfabeto? ", a.isalpha())
print("É alfanumerico? ", a.isalnum())
print("Estar em maiúsculas? ", a.isupper())
print("Estar em minúsculas? ", a.islower())
print("Estar capitalizada? ", a.istitle())